
import { makeStyles } from '@material-ui/core/styles';

export const styles = makeStyles((theme) => ({
  block: {
    display: "inline-block",
    textAlign: 'center'
  },
  pageTitle: {
    color: "#A958F4",
    fontWeight: 'bold',
    textAlign: 'center',
    marginTop: theme.spacing(3)
  },
  save:{
    backgroundColor: "#A958F4"
  },
  rectangle9: { // need to fix the retangle box position, https://www.w3schools.com/css/css_positioning.asp
    position: "relative",
    flex: "auto",
    width: "360px",
    height: "360px",
    left: "0px",
    top: "0",
    display: "inline-block",
    margin: "15px",
    // border: "1px solid #000000",
    letterSpacing: "0",
    spacine: "10px",
    verticalAlign: "top",
    boxSizing: "borderBox",
    boxShadow: "0px 4px 4px rgba(0, 0, 0, 0.25), 0px 4px 4px rgba(0, 0, 0, 0.25)",
    borderRadius: "20px",
    backgroundColor:"white"
  },
  rectangleplus: { // need to fix the retangle box position, https://www.w3schools.com/css/css_positioning.asp
    position: "relative",
    flex: "auto",
    width: "360px",
    height: "360px",
    left: "65px",
    top: "0",
    display: "inline-block",
    margin: "15px",
    // border: "1px solid #000000",
    letterSpacing: "0",
    spacine: "10px",
    verticalAlign: "top",
    boxSizing: "borderBox",
    boxShadow: "0px 4px 4px rgba(0, 0, 0, 0.25), 0px 4px 4px rgba(0, 0, 0, 0.25)",
    borderRadius: "20px",
  },
  image: {
    position: "relative",
    // left: "0%",
    // right: "0%",
    // top: "0%",
    // bottom: "40.05%",
    left: "0%",
    right: "0%",
    top: "0%",
    bottom: "50.05%",
    width: "180px",
    height: "180px",
    // background: url(sample.jpg),
    // borderRadius: "20px 20px 0px 0px",
  },
  imageadd: {
    position: "relative",
    // left: "0%",
    // right: "0%",
    // top: "0%",
    // bottom: "40.05%",
    left: "0%",
    right: "0%",
    top: "0%",
    bottom: "50.05%",
    width: "90px",
    height: "90px",
    // background: url(sample.jpg),
    // borderRadius: "20px 20px 0px 0px",
  },
  logo: {
    position: "relative",
    // left: "0%",
    // right: "0%",
    // top: "0%",
    // bottom: "40.05%",
    left: "0%",
    right: "0%",
    top: "0%",
    bottom: "50.05%",
    width: "250px",
    height: "160px",
    // background: url(sample.jpg),
    borderRadius: "20px 20px 0px 0px",
  },
  itemName: {  // Name issue
    position: "relative",
   
    // height: "40%",
    textAlign: 'center',
    fontFamily: "Romanesco",
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "32px",
    lineHeight: "41px",

    color: "black",
  },
  rate: {
    position: "relative",
    // left: "74.72%",
    // right: "7.78%",
    // top: "60.17%",
    // bottom: "27.96%",
    margin: "auto",          /* make text in center*/
    display: "flex", 
    textAlign: "center",
    justifyContent: "center",
    alignItems: "center",
    
    fontFamily: "Palanquin Dark",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "18px",
    lineHeight: "40px",
    /* identical to box height */
    // display: "flex",
    // alignitems: "flex-end",
    textTransform: "capitalize",
    color: "rgba(183, 43, 43, 0.93)",

    /* Orange */
    textShadow: "0px 4px 4px rgba(0, 0, 0, 0.25)",
  },
  ellipse: {
    position: "relative",
    left: "82.78%",
    right: "6.11%",
    height: "40px",
    width: "40px",
    backgroundColor: "rgba(246, 216, 216, 1)",
    borderRadius: "50%",
    display: "inline-block",
  },
  deliveryInfo: {
    position: "relative",
    left: "6.67%",
    right: "3.06%",
    width: "60%",
    // height: "70%",
    fontfamily: "Roboto",
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "14px",
    lineHeight: "16px",

    color: "black",
  },
  price:{
    position: "relative",
    left: "6.67%",
    right: "3.06%",
    width: "60%",
    //height: "14px",
    fontfamily: "Roboto",
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "20px",
    lineHeight: "16px",
    color: "black",
  },
  itemDesc: {
    position: "relative",
    left: "6.67%",
    right: "500px",
    width: "60%",
    fontfamily: "Arial",
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "14px",
    lineHeight: "16px",
    color: "black",
  }
}));

export default styles;