# Status: Success
# Description: Driver checks in
# State Before: Driver state for the day is always initialized to 'idle'
# State After: Driver state for the day is set to 'checkin'
POST http://localhost:5000/twilio/sms HTTP/1.1
Content-Type: application/json

{
  "ToCountry": "US",
  "ToState": "TX",
  "SmsMessageSid": "SMce3fbbee7d9982da6e14863ec3266cbf",
  "NumMedia": "0",
  "ToCity": "",
  "FromZip": "95602",
  "SmsSid": "SMce3fbbee7d9982da6e14863ec3266cbf",
  "FromState": "CA",
  "SmsStatus": "received",
  "FromCity": "AUBURN",
  "Body": "check-in",
  "FromCountry": "US",
  "To": "+14085210010",
  "ToZip": "",
  "NumSegments": "1",
  "MessageSid": "SMce3fbbee7d9982da6e14863ec3266cbf",
  "AccountSid": "AC6685ca9e7a76c443fab749516bdda464",
  "From": "+15304013190",
  "ApiVersion": "2010-04-01"
}

###

# Status: Fail
# Description: Driver tries to check in but isn't a driver
# State Before: There is no before
# State After: Driver recieves text that they should sign up to drive @ kahzum.com
POST http://localhost:5000/twilio/sms HTTP/1.1
Content-Type: application/json

{
  "ToCountry": "US",
  "ToState": "TX",
  "SmsMessageSid": "SMce3fbbee7d9982da6e14863ec3266cbf",
  "NumMedia": "0",
  "ToCity": "",
  "FromZip": "95602",
  "SmsSid": "SMce3fbbee7d9982da6e14863ec3266cbf",
  "FromState": "CA",
  "SmsStatus": "received",
  "FromCity": "AUBURN",
  "Body": "check-in",
  "FromCountry": "US",
  "To": "+14085210010",
  "ToZip": "",
  "NumSegments": "1",
  "MessageSid": "SMce3fbbee7d9982da6e14863ec3266cbf",
  "AccountSid": "AC6685ca9e7a76c443fab749516bdda464",
  "From": "+1234567211",
  "ApiVersion": "2010-04-01"
}