POST http://localhost:5000/routing/computeRoute
Content-Type: application/json

{   "driverIDs" :["5fa4a4a61321c028c5b72ede"],
    "startLocation" : ["1010 Fair st, Santa Cruz, CA"],
"addressPairs": ["435 Front St, Santa Cruz, CA 95060","710 College Ten Rd, Santa Cruz, CA 95064","1148 soquel ave, Santa Cruz, CA 95062","183 chestnut st, Santa Cruz, CA 95060"]}