POST http://localhost:5000/routing/saveRoutingOutput
Content-Type: application/json

{
  "routes": [
    {
      "driverId": "5fbef667f33d2e0037d77672",
      "stop_ids": [
        0,
        1,
        3,
        4,
        2
      ],
      "route": [
        {
          "address": "1010 Fair st, Santa Cruz, CA",
          "orderId": ""
        },
        {
          "address": "435 Front St, Santa Cruz, CA 95060",
          "orderId": "5fa4d773731030389a098551"
        },
        {
          "address": "435 Front St, Santa Cruz, CA 95060",
          "orderId": "5fa4a4321321c028c5b72edd"
        },
        {
          "address": "435 Front St, Santa Cruz, CA 95060",
          "orderId": "5f9e1dc8f37335229c1e1896"
        },
        {
          "address": "1148 soquel ave, Santa Cruz, CA 95062",
          "orderId": "5f94ac5610989b2208a9d7a4"
        },
        {
          "address": "602 Laurel st, Santa Cruz, CA 95062",
          "orderId": "5fa4a4321321c028c5b72edd"
        },
        {
          "address": "602 Laurel st, Santa Cruz, CA 95062",
          "orderId": "5f94ac5610989b2208a9d7a4"
        },
        {
          "address": "602 Laurel st, Santa Cruz, CA 95062",
          "orderId": "5fa4d8961deac339441f0e1f"
        },
        {
          "address": "510 Porter-kresge rd, Santa Cruz, CA 95064",
          "orderId": "5fa4d773731030389a098551"
        },
        {
          "address": "710 College Ten Rd, Santa Cruz, CA 95064",
          "orderId": "5fa4d8961deac339441f0e1f"
        },
        {
          "address": "710 College Ten Rd, Santa Cruz, CA 95064",
          "orderId": "5f9e1dc8f37335229c1e1896"
        }
      ],
      "routeTime": 2054
    }
  ],
  "totalTime": 2054
}