GET http://localhost:5000/business/business-info?business=5f94ac5610989b2208a9d7a4
Accept: application/json


###
GET http://localhost:5000/business/completed-orders?business=5fa4a33634b8df278531dfd5&N=10
Content-Type: application/json

###

POST http://localhost:5000/business/delete-order
Content-Type: application/json

{"business": "5f94ac5610989b2208a9d7a4", "order": "5f9a2247176e8a97179bf978"}

###
PATCH http://localhost:5000/business/update-business
Content-Type: application/json

{ "business": "5f94ac5610989b2208a9d7a4", "businessName": "Daniel's Cookies"}

###
POST http://localhost:5000/business/sign-in
Content-Type: application/json

{"ownerEmail": "smith2@gmail.com"}

###
POST http://localhost:5000/business/add-business
Content-Type: application/json

{ "businessName": "Sams Cookie", "businessPhone": "530-401-3190", "pickupAddress": "123 great lane", "ownerFullName": "Sam Smith", "ownerEmail": "smith2@gmail.com", "ownerPhone":"909-999-5890" }

###
GET http://localhost:5000/business/validate-address?address=arbok
Accept: application/json

###
GET http://localhost:5000/business/validate-address?address=300 Main Street, Santa Cruz, CA
Accept: application/json

