POST http://localhost:5000/driver/complete-orders
Content-Type: application/json

{
  "driver": "5fbef667f33d2e0037d77672",
  "order": "5fa4a4321321c028c5b72edc",
  "imageUrl": "https://api.twilio.com/2010-04-01/Accounts/AC6685ca9e7a76c443fab749516bdda464/Messages/MM4c832e31b5220294c1a6be1a1301afca/Media/ME73ae89192b99dbaf2dd5e4ff87c925e1"
}

###
POST http://localhost:5000/driver/assign-order
Content-Type: application/json

{
  "driver": "5fa2f7774964eff6d38da6f0",
  "order": "5f979eeffcb7a34058b5415f"
}

###
GET http://localhost:5000/driver/5f908e3cb4561c7fb8b9c4b8
Accept: application/json

###
GET http://localhost:5000/driver/all-drivers
Accept: application/json

###
POST http://localhost:5000/driver/add-driver
Content-Type: application/json

{ "fullName": "Mason Pierce","phone": "530-401-3190","email": "malapier@ucsc.edu","startLocation": "300 Main Street, Santa Cruz, CA", "locality": "santa cruz" }

