GET localhost:5000/driver/5f908e3cb4561c7fb8b9c4b8
Accept: application/json

###
GET localhost:5000/driver/all-drivers
Accept: application/json

###
POST localhost:5000/driver/add-driver
Content-Type: application/json

{ "fullName": "John Smith","phone": "408-435-5532","email": "smith@gmail.com" }

