###########
# Run each of these requests in order to test the full flow of the backend
###########
# Saved vars from steps:
# 1. 5fa4a33634b8df278531dfd5
# 2. 5fa4a4321321c028c5b72edc && 5fa4a4321321c028c5b72edd
# 3. 5fa4a4a61321c028c5b72ede
# 4. 
# 5. 
# 6. 
###

# Step 1: add a business IMPORTANT: save _id from the request response!
POST http://localhost:5000/business/add-business
Content-Type: application/json

{ "businessName": "Mason's test", "businessPhone": "530-401-3190", "pickupAddress": "2660 Sherwood Way, Meadow Vista, CA 95722", "ownerFullName": "Mason Owner", "ownerEmail": "masonOwner@gmail.com", "ownerPhone":"530-401-3190" }

###
# Step 2: add an order to the business (make sure to copy the _id from the response above and paste it into the "business" field)
# IMPORTANT: save _id's from the request response!
POST http://localhost:5000/order/add-orders
Content-Type: application/json

{"business": "5fa4a33634b8df278531dfd5",
   "orders": [{
     "address": "300 Main St., Santa Cruz, CA 95060",
     "customer_name": "Mason Customer2",
     "customer_phone": "530-401-3190"
   },
   {
     "address": "300 Main St., Santa Cruz, CA 95060",
     "customer_name": "Jeff Customer4",
     "customer_phone": "530-401-3190"
   }]
}

###
# Step 3: Create a driver. IMPORTANT: save _id from the request response!
POST http://localhost:5000/driver/add-driver
Content-Type: application/json

{ "fullName": "Mason Pierce","phone": "530-401-3190","email": "malapier@ucsc.edu" }

###
# Step 4: Assign that driver to the above orders. (paste both the driver id and the order id below)
POST http://localhost:5000/driver/assign-order
Content-Type: application/json

{
  "driver": "5fa4a4a61321c028c5b72ede",
  "order": "5fa4d8961deac339441f0e1f"
}

###
# Step 5: Simulate dropoff (will send text to customer number (with an image) and driver number listed below)
POST http://localhost:5000/twilio/sms HTTP/1.1
Content-Type: application/json

{
  "AccountSid": "AC6685ca9e7a76c443fab749516bdda464",
  "ApiVersion": "2010-04-01",
  "Body": "Dropoff",
  "From": "+15304013190",
  "FromCity": "AUBURN",
  "FromCountry": "US",
  "FromState": "CA",
  "FromZip": "95602",
  "MediaContentType0": "image/jpeg",
  "MediaUrl0": "https://api.twilio.com/2010-04-01/Accounts/AC6685ca9e7a76c443fab749516bdda464/Messages/MM4c832e31b5220294c1a6be1a1301afca/Media/ME73ae89192b99dbaf2dd5e4ff87c925e1",
  "MessageSid": "MM4c832e31b5220294c1a6be1a1301afca",
  "NumMedia": 1,
  "NumSegments": 1,
  "SmsMessageSid": "MM4c832e31b5220294c1a6be1a1301afca",
  "SmsSid": "MM4c832e31b5220294c1a6be1a1301afca",
  "SmsStatus": "received",
  "To": "+14302390178",
  "ToCity": "no value",
  "ToCountry": "US",
  "ToState": "TX",
  "ToZip": "no value"
}

###