POST http://localhost:5000/invoice/add-invoice
Content-Type: application/json

{"email": "ramissir@ucsc.edu"}
###
PATCH http://localhost:5000/invoice/add-items
Content-Type: application/json

{"invoiceID":"60940f8b0b66217a941aa9a4","items":{"scarf": [4,1]}}
###