# SHOULD FAIL: No image
# Post a message to Twilio with the text "Dropoff"
POST http://localhost:5000/twilio/sms HTTP/1.1
Content-Type: application/json

{
  "ToCountry": "US",
  "ToState": "TX",
  "SmsMessageSid": "SMce3fbbee7d9982da6e14863ec3266cbf",
  "NumMedia": "0",
  "ToCity": "",
  "FromZip": "95602",
  "SmsSid": "SMce3fbbee7d9982da6e14863ec3266cbf",
  "FromState": "CA",
  "SmsStatus": "received",
  "FromCity": "AUBURN",
  "Body": "dropoff",
  "FromCountry": "US",
  "To": "+14302390178",
  "ToZip": "",
  "NumSegments": "1",
  "MessageSid": "SMce3fbbee7d9982da6e14863ec3266cbf",
  "AccountSid": "AC6685ca9e7a76c443fab749516bdda464",
  "From": "+15304013190",
  "ApiVersion": "2010-04-01",
}

###

# SHOULD SUCCEED: 
# Post a message to Twilio with the text "Dropoff" and an image of an umbrella
POST http://localhost:5000/twilio/sms HTTP/1.1
Content-Type: application/json

{
  "AccountSid": "AC6685ca9e7a76c443fab749516bdda464",
  "ApiVersion": "2010-04-01",
  "Body": "Dropoff",
  "From": "+15304013190",
  "FromCity": "AUBURN",
  "FromCountry": "US",
  "FromState": "CA",
  "FromZip": "95602",
  "MediaContentType0": "image/jpeg",
  "MediaUrl0": "https://api.twilio.com/2010-04-01/Accounts/AC6685ca9e7a76c443fab749516bdda464/Messages/MM4c832e31b5220294c1a6be1a1301afca/Media/ME73ae89192b99dbaf2dd5e4ff87c925e1",
  "MessageSid": "MM4c832e31b5220294c1a6be1a1301afca",
  "NumMedia": 1,
  "NumSegments": 1,
  "SmsMessageSid": "MM4c832e31b5220294c1a6be1a1301afca",
  "SmsSid": "MM4c832e31b5220294c1a6be1a1301afca",
  "SmsStatus": "received",
  "To": "+14302390178",
  "ToCity": "no value",
  "ToCountry": "US",
  "ToState": "TX",
  "ToZip": "no value"
}

###

# Testing temporary endpoint: ADD order
# Post a method that tests the endpoint called by the db to notify us of an order change
POST http://localhost:5000/twilio/send-order-info HTTP/1.1
Content-Type: application/json

{
   "event":{
      "_id":{
         "_data":"825FBE927E000000012B022C0100296E5A100416602F87A9764D0AB12FF5934D0020F146645F696400645FBE927E312AAB00569302DA0004"
      },
      "operationType":"insert",
      "clusterTime":{
         "$timestamp":{
            "t":1606324862,
            "i":1
         }
      },
      "fullDocument":{
         "_id":{
            "$oid":"5fbe927e312aab00569302da"
         },
         "business":{
            "$oid":"5fbc86677a200121dae404a1"
         },
         "customer_name":"This is a test order to see if this works",
         "customer_phone":"123-456-7890",
         "address":"Testing address",
         "createdAt":{
            "$date":{
               "$numberLong":"1606324862136"
            }
         },
         "updatedAt":{
            "$date":{
               "$numberLong":"1606324862136"
            }
         },
         "__v":{
            "$numberInt":"0"
         }
      },
      "ns":{
         "db":"kahzumProd",
         "coll":"pending orders"
      },
      "documentKey":{
         "_id":{
            "$oid":"5fbe927e312aab00569302da"
         }
      }
   }
}

###

# Testing temporary endpoint: UPDATE order
# Post a method that tests the endpoint called by the db to notify us of an order change
POST http://localhost:5000/twilio/send-order-info HTTP/1.1
Content-Type: application/json

{
   "event":{
      "_id":{
         "_data":"825FBE92A40000000E2B022C0100296E5A100416602F87A9764D0AB12FF5934D0020F146645F696400645FBE927E312AAB00569302DA0004"
      },
      "operationType":"update",
      "clusterTime":{
         "$timestamp":{
            "t":1606324900,
            "i":14
         }
      },
      "fullDocument":{
         "_id":{
            "$oid":"5fbe927e312aab00569302da"
         },
         "business":{
            "$oid":"5fbc86677a200121dae404a1"
         },
         "customer_name":"This is a test order to see if this",
         "customer_phone":"123-456-7890",
         "address":"Testing address",
         "createdAt":{
            "$date":{
               "$numberLong":"1606324862136"
            }
         },
         "updatedAt":{
            "$date":{
               "$numberLong":"1606324900389"
            }
         },
         "__v":{
            "$numberInt":"0"
         }
      },
      "ns":{
         "db":"kahzumProd",
         "coll":"pending orders"
      },
      "documentKey":{
         "_id":{
            "$oid":"5fbe927e312aab00569302da"
         }
      },
      "updateDescription":{
         "updatedFields":{
            "customer_name":"This is a test order to see if this",
            "updatedAt":{
               "$date":{
                  "$numberLong":"1606324900389"
               }
            }
         },
         "removedFields":[
            
         ]
      }
   }
}

###

# Testing temporary endpoint: DELETE order
# Post a method that tests the endpoint called by the db to notify us of an order change
POST http://localhost:5000/twilio/send-order-info HTTP/1.1
Content-Type: application/json

{
   "event":{
      "_id":{
         "_data":"825FBE9321000000072B022C0100296E5A100416602F87A9764D0AB12FF5934D0020F146645F696400645FBE927E312AAB00569302DA0004"
      },
      "operationType":"delete",
      "clusterTime":{
         "$timestamp":{
            "t":1606325025,
            "i":7
         }
      },
      "ns":{
         "db":"kahzumProd",
         "coll":"pending orders"
      },
      "documentKey":{
         "_id":{
            "$oid":"5fbe927e312aab00569302da"
         }
      }
   }
}

###